### ISSUE TITLE
Don't use hostname for CN in CSR

### ISSUE THREAD

**Issue by rentallect** [openziti/sdk-golang#115]
`ziti/enroll/enroll.go` uses `hostname` for `CN` in `CSR` used during enrollment. Hostnames can contain underscores. This is a problem because the golang asn1 parser does not support underscores in `printablestring` fields of asn1 structures (like CSRs). Upshot is that attempts to enroll from hosts that have a name containing an underscore will fail.

**Comment by plorenz** [comment]
@rentallect any thoughts on what the right thing to do is here? Strip the underscores out? Use the identity id? Use a UUID?

**Comment by dovholuknf** [comment]
Someone's reading old issues! This is kind of a problem since there's really 'no good way'. Maybe base64 encoding the CN is the only good answer here? I'm surprised this hasn't been an issue before... Makes me want to make a hostname with underscores just to try it.

I'm inclined to close it as a 'known issue' though...

**Comment by rentallect** [comment]
Stripping the (potential) underscores out of the hostname seems like an expedient way out of this (admittedly limited) edge-case predicament.  Given that it has been almost 3 years since this issue was encountered, and never re-encountered since then, the @dovholuknf suggestion of closing as a known issue is fine too.

**Comment by dovholuknf** [comment]
I just worry there are people out there that have done:
* server1
* server_1

Those people will have a 'bad time' and it'll be a hard bug to track down and other silly things like that. I'm for "closed as known issue" :) or base64'ing a hostname containing an underscore (and maybe padding to avoid equals signs? if base 64'ed)

But as @rentallect says, since this is 3 yrs old, i vote "just close it" for now

**Comment by plorenz** [comment]
According to @andrewpmartinez CN isn't used for validation, SANs are used instead. Also, these are all client certs, so we're not checking those anyway. I'm going to switch it to use the identity id, which only use characters that are allowed by asn1 printablestrings.

**Comment by ekoby** [comment]
using id makes it consistent with other SDKs
